# name: validations

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
    
# jobs:
#   validate-yaml:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Validate YAML
#         run: |
#           cat ./service-accounts/service-accounts.yaml | yq e '.serviceAccounts[].name' - | sort | uniq -d > duplicates.txt
#           DUPLICATES=$(cat duplicates.txt)

#           if [[ -n "$DUPLICATES" ]]; then
#             echo "Duplicate service account names found:"
#             echo "$DUPLICATES"
#             exit 1
#           else
#             echo "No duplicate service account names found."
#           fi
